# Generated by Django 2.1.7 on 2019-04-02 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.CharField(max_length=200)),
                ('title_text', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('article_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herald.Article')),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herald.Author')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herald.Author'),
        ),
    ]
