# Generated by Django 2.2 on 2019-04-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herald', '0002_auto_20190406_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='commnet_text',
        ),
    ]
