# Generated by Django 2.2 on 2019-04-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herald', '0003_auto_20190406_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet_text',
            new_name='comment_text',
        ),
    ]
