# Generated by Django 2.2 on 2019-04-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herald', '0004_auto_20190406_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_comment',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
